name: NPM Publish

on:
  workflow_call:
    secrets:
        NPM_TOKEN:
          required: true
  workflow_dispatch:

jobs:
  publish:
    if: github.repository_owner == 'viamrobotics'
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install and Build 🔧
        run: |
          npm ci --prefix ./web/frontend --audit=false
          npm run build-npm --prefix ./web/frontend

      - name: Publish
        uses: JS-DevTools/npm-publish@v2
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: ./web/frontend/package.json
          access: public
